# Generated by Django 3.2.12 on 2022-05-14 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='категория')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('manager', models.CharField(max_length=255, verbose_name='менеджер')),
                ('manager_phone', models.IntegerField(verbose_name='телефон менеджера')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='группа')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supply.category', verbose_name='категория')),
            ],
        ),
        migrations.CreateModel(
            name='TypeStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='тип склада')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название склада')),
                ('type_storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage', to='supply.typestorage', verbose_name='тип склада')),
            ],
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supply.category', verbose_name='категория')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supply.group', verbose_name='группа')),
            ],
        ),
    ]
