# Generated by Django 3.2.12 on 2022-06-16 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='категория')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('manager', models.CharField(max_length=255, verbose_name='менеджер')),
                ('manager_phone', models.IntegerField(verbose_name='телефон менеджера')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='группа')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supply.category', verbose_name='категория')),
            ],
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supply.category', verbose_name='категория')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supply.group', verbose_name='группа')),
            ],
        ),
        migrations.CreateModel(
            name='TypeStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='тип склада')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название склада')),
                ('type_storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage', to='supply.typestorage', verbose_name='тип склада')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
                ('is_booking', models.BooleanField(default=False)),
                ('is_order', models.BooleanField(default=False)),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specification', to='supply.nomenclature', verbose_name='номенклатура')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='production.productorder', verbose_name='заказ на производство')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_order', models.BooleanField(default=False)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase', to='supply.contractor', verbose_name='поставщик')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase', to='supply.nomenclature', verbose_name='номенклатура')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase', to='supply.storage', verbose_name='склад')),
            ],
        ),
    ]
