# Generated by Django 3.2.12 on 2022-05-17 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20220517_1543'),
        ('supply', '0005_purchase_is_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase', to='supply.contractor', verbose_name='поставщик'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase', to='supply.storage', verbose_name='склад'),
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specification', to='supply.nomenclature', verbose_name='номенклатура')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='production.productorder', verbose_name='заказ на производство')),
            ],
        ),
    ]
