# Generated by Django 3.2.12 on 2022-06-16 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_specification_done', models.BooleanField(default=True)),
                ('name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='crm.product', verbose_name='название')),
            ],
        ),
    ]
