# Generated by Django 3.2.12 on 2022-05-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20220517_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='name',
        ),
    ]
