# Generated by Django 3.2.12 on 2022-05-30 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_product'),
        ('production', '0003_remove_productorder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='crm.product', verbose_name='название'),
        ),
    ]
