# Generated by Django 3.2.12 on 2022-03-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_address_addressarea_addresscountry_addressregion_addressstreet_addresstown_order_typepay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typepay',
            name='type_pay',
            field=models.CharField(max_length=151, verbose_name='тип оплаты'),
        ),
    ]
