# Generated by Django 3.2.12 on 2022-05-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_order_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_create']},
        ),
        migrations.AlterField(
            model_name='order',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
