# Generated by Django 3.2.12 on 2022-03-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_typepay_type_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_second_pay',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='typepay',
            name='type_pay',
            field=models.CharField(max_length=150, verbose_name='тип оплаты'),
        ),
    ]
