# Generated by Django 3.2.12 on 2022-05-30 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_order_status_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_done',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_pre_pay',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pre_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, verbose_name='предоплата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pre_pay_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_pay_types', to='crm.typepay', verbose_name='тип предоплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, verbose_name='сумма заказа'),
        ),
    ]
