# Generated by Django 3.2.12 on 2022-05-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20220530_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
