# Generated by Django 3.2.12 on 2022-05-30 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_order_date_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measuring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measuring', models.FileField(blank=True, upload_to='crm/', verbose_name='замер')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='measuring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='crm.measuring', verbose_name='замер'),
        ),
    ]
