# Generated by Django 3.2.12 on 2022-05-30 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20220530_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='measuring',
        ),
        migrations.AddField(
            model_name='measuring',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measuring', to='crm.product', verbose_name='изделие'),
        ),
    ]
