# Generated by Django 3.2.12 on 2022-05-31 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_auto_20220530_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuring',
            name='measuring',
            field=models.FileField(blank=True, upload_to='measuring/', verbose_name='замер'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.FileField(blank=True, upload_to='project/', verbose_name='проект')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='crm.product', verbose_name='изделие')),
            ],
        ),
    ]
