# Generated by Django 3.2.12 on 2022-06-03 23:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_auto_20220531_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 23, 5, 8, 201703, tzinfo=utc)),
        ),
    ]
