# Generated by Django 3.2.12 on 2022-06-03 23:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_comment_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 23, 6, 6, 425836, tzinfo=utc)),
        ),
    ]
