# Generated by Django 3.2.12 on 2022-06-03 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_alter_comment_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
