# Generated by Django 3.2.12 on 2022-06-03 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_alter_comment_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
