# Generated by Django 3.2.12 on 2022-06-05 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_auto_20220605_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 5, 23, 7, 49, 813072), null=True),
        ),
    ]
