# Generated by Django 3.2.12 on 2022-06-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_auto_20220605_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
