# Generated by Django 3.2.12 on 2022-06-06 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_alter_task_is_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-date'], 'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_create',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='date_create',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_create',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='date_create',
            new_name='date',
        ),
    ]
