# Generated by Django 3.2.12 on 2022-06-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_2', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
