# Generated by Django 3.2.12 on 2022-05-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drag',
            name='name_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
