# Generated by Django 3.2.12 on 2022-05-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drag', '0002_alter_drag_name_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drag',
            options={'ordering': ['name']},
        ),
    ]
